return {
	"nvim-treesitter/nvim-treesitter",
	main = "nvim-treesitter.configs",
	branch = "master",
	event = "VeryLazy",
	build = ":TSUpdate",
	opts = {
		ensure_installed = {
			"bash",
			"c",
			"cpp",
			"css",
			"diff",
			"git_config",
			"gitcommit",
			"gitignore",
			"go",
			"html",
			"javascript",
			"json",
			"lua",
			"luadoc",
			"markdown",
			"markdown_inline",
			"python",
			"query",
			"regex",
			"rust",
			"toml",
			"typescript",
			"vim",
			"vimdoc",
			"yaml",
		},
		highlight = { enable = true },
		indent = { enable = true },
		auto_install = true,
		incremental_selection = {
			enable = true,
			keymaps = {
				init_selection = "<CR>",
				node_incremental = "<CR>",
				scope_incremental = "<leader>s",
				node_decremental = "<BS>",
			},
		},
	},
}
